spring:
  datasource:
    url: jdbc:mysql://localhost:3306/collaboration
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: jnissi92@gmail.com
    password: opipynpskjlvttpp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?

jwt:
  secret:
    key: LjfT+P7fxz3oEt/Tzr+BL6MFhQgn5r9hvT/1Ir1Zs9y0y00KZDeZRlBT5pE2LC3mJ78jjS4yXFlBT4wmh/Q/Fw==

aes:
  secret:
    key: wHwZn0Pi34Pl2NlYKqw0XZEXmtQ+BdTnQRqLNHrFmMo=