spring:
  config:
    activate:
      on-profile: performance
  datasource:
    url: jdbc:mysql://localhost:3306/collaboration_product
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 20
  logging:
    level:
      root: ERROR
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8082
  tomcat:
    threads:
      max: 500
    max-connections: 10000
    accept-count: 5000